image: "dothanhtrung/bevy-dev:latest"

before_script:
  - rm -f .cargo/config.toml
  - rm -f rust-toolchain.toml

cache: &global_cache
  key: cargo_cache
  paths:
    - target/
    - .cargo/registry/index
    - .cargo/registry/cache
  policy: pull-push

variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/.cargo

#check:
#  stage: build
#  script:
#    - rustc --version && cargo --version  # Print version info for debugging
#    - cargo check --examples
#    - cargo check --features=experimental --examples
#  cache:
#    <<: *global_cache
#    policy: pull

test:
  stage: test
  script:
    - cargo test --tests
    - find . -mtime +30 -delete || true
  rules:
    - changes:
      - Cargo.toml
      - src/**/*
      - examples/**/*
      - tests/**/*

release_build:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - cargo build --release
    - tar cJvf dialogue-editor_${CI_COMMIT_TAG}.linux.x86-64.tar.xz -C target/release dialogue-editor
    - find . -mtime +30 -delete || true
  artifacts:
    paths:
      - dialogue-editor_*.tar.xz
