[package]
name = "dialogue-editor"
version = "0.0.3"
edition = "2024"

[dependencies]
slint = {version = "1.17", default-features = false, features = ["backend-default", "renderer-femtovg", "renderer-software", "compat-1-2", "std"]}
serde = { version="1.0", default-features = false }
postcard = { version = "1.1", features = ["alloc"], default-features = false }
simple_crypt = { version = "0.2", default-features = false, optional = true }
ron = { version = "0.12" , default-features = false, features = ["std"]}
anyhow = { version = "1.0" , default-features = false}
xxhash-rust = {version = "0.8", default-features = false, features = ["xxh3"] }
isolang = {version = "2.4", features = ["serde"], default-features = false}
tracing = {version = "0.1", default-features = false}
tracing-subscriber = { version = "0.3" , default-features = false, features = ["env-filter", "fmt"]}
regex = {version = "1.13", default-features = false, features = ["std", "unicode", "perf"]}
rfd = {version = "0.17", default-features = false, features = ["wayland", "xdg-portal"]}
clap = { version = "4.6", default-features = false, features = ["derive", "std", "color", "help", "usage", "error-context"] }

[build-dependencies]
slint-build = "1.17"

[features]
default = []
crypt = ["simple_crypt"]

[profile.release]
codegen-units = 1
lto = true
strip = true

[lints.clippy]
map_entry = "allow"
