import {
    TextEdit,
    Button,
    VerticalBox,
    HorizontalBox,
    ListView,
    ComboBox,
} from "std-widgets.slint";
import { EditableTextBox, UiDialogue, DialogueBox } from "app_widgets.slint";


export component AppWindow inherits Window {
    in-out property <string> file_path;
    in-out property <[string]> classes;
    in-out property <[string]> states;
    in-out property <[UiDialogue]> dialogues;
    in-out property <[string]> lang-list;

    callback request-save();
    callback request-load(string);
    callback select-class(string);
    callback remove-class(string);
    callback add-class(string);
    callback rename-class(string, string); // old name, new name
    callback select-state(string);
    callback remove-state(string);
    callback add-state(string);
    callback rename-state(string, string); // old name, new name
    callback add-dialog(string, string, string, string);
    callback remove-dialog(int);

    callback new_trans_content(int, string, string);
    callback new_affect(int, string, string);

    VerticalBox {
        HorizontalBox {
            // Class actor
            VerticalBox {
                ListView {
                    for class_name[i] in classes: EditableTextBox {
                        value: class_name;
                        select => {
                            select-class(class_name);
                        };
                        submit(new_name) => {
                            rename-class(class_name, new_name);
                        };
                        delete => {
                            remove-class(class_name);
                        };
                    }
                }

                new_class := TextInput {
                    text: "New class";
                }

                Button {
                    text: "Add";
                    clicked => {
                        root.add-class(new_class.text);
                    };
                }
            }

            // Dialogue State
            VerticalBox {
                ListView {
                    for state_name in states: EditableTextBox {
                        value: state_name;
                        select => {
                            select-state(state_name);
                        };
                        submit(new_name) => {
                            rename-state(state_name, new_name);
                        };
                        delete => {
                            remove-state(state_name);
                        };
                    }
                }

                new_state := TextInput {
                    text: "New state";
                }

                Button {
                    text: "Add";
                    clicked => {
                        root.add-state(new_state.text);
                    }
                }
            }

            // Dialogue content
            VerticalBox {
                ListView {
                    for dialog[i] in dialogues: DialogueBox {
                        dialogue: dialog;
                        lang_list: lang-list;
                        class_list: classes;
                        state_list: states;

                        new_lang_content(lang, content) => {
                            new_trans_content(i, lang, content);
                        };
                        new_affect(class, state) => {
                            new_affect(i, class, state);
                        };
                    }
                }

                VerticalBox {
                    HorizontalBox {
                        new_lang := ComboBox { }

                        new_dialog := TextEdit { }
                    }

                    HorizontalBox {
                        new_affect_class := ComboBox { }

                        new_affect_state := ComboBox { }
                    }

                    Button {
                        text: "Add";
                        clicked => {
                            root.add-dialog(new_lang.current-value, new_dialog.text, new_affect_class.current-value, new_affect_state.current-value);
                        }
                    }
                }
            }
        }

        file_path_input := TextInput {
            text: root.file_path;
        }

        Button {
            text: "Load";
            clicked => {
                root.request-load(file_path_input.text);
            }
        }

        Button {
            text: "Save";
            clicked => {
                root.request-save();
            }
        }
    }
}
