import {
    TextEdit,
    Button,
    VerticalBox,
    HorizontalBox,
    ListView,
    ComboBox,
    LineEdit,
    Palette,
} from "std-widgets.slint";
import {
    EditableTextBox,
    UiDialogue,
    DialogueBox,
    SelectableBox,
} from "app_widgets.slint";
import { StatusBar } from "status_bar.slint";

// TODO: Status bar, Config UI, Notification

export component AppWindow inherits Window {
    in-out property <string> file_path;
    in-out property <int> file_format;
    in-out property <string> encrypt_key;
    in-out property <[string]> classes;
    in-out property <[string]> states;
    in-out property <[string]> dialogues;
    in-out property <UiDialogue> dialogue;
    in-out property <[string]> lang_list;
    in-out property <[string]> state_list;

    in-out property <bool> is_saved: true;

    in-out property <bool> enable_crypt: false;

    property <int> selecting_class: -1;
    property <int> selecting_state: -1;
    property <int> selecting_dialog: -1;

    callback request-save(string, int, string);
    callback request-load(string, int, string);

    callback select-class(string);
    callback remove-class(string);
    callback add-class(string);
    callback rename-class(string, string); // old name, new name
    
    callback select-state(string);
    callback remove-state(string);
    callback add-state(string);
    callback rename-state(string, string); // old name, new name

    callback select-dialog(int);
    callback add-dialog();
    callback remove-dialog(int);

    callback new_lang_content(string, string); // lang, content
    callback new_affect(string, string); // affect_class, affect_state
    callback update_content(UiDialogue); // dialog
    callback delete_content(string);
    callback delete_affect(string);

    callback search(string, string);
    callback file_picker();

    VerticalBox {
        HorizontalBox {
            // Class actor
            Rectangle {
                width: 20%;

                VerticalBox {
                    LineEdit {
                        placeholder-text: "Search...";
                        accepted(text) => {
                            search(text, "");
                        }
                    }

                    TouchArea {
                        clicked => {
                        // root.selecting_class = -1;
                    }

                        ListView {
                            for class_name[i] in classes: EditableTextBox {
                                value: class_name;
                                selected: {
                                    root.selecting_class == i
                                };
                                background: {
                                    if (root.selecting_class == i) {
                                        Palette.selection-background
                                    } else {
                                        Palette.background
                                    }
                                };
                                select => {
                                    select-class(class_name);
                                    root.selecting_class = i;
                                    root.selecting_state = -1;
                                    root.selecting_dialog = -1;
                                };
                                submit(new_name) => {
                                    rename-class(class_name, new_name);
                                    root.is_saved = false;
                                };
                                delete => {
                                    remove-class(class_name);
                                    root.is_saved = false;
                                };
                            }
                        }
                    }

                    HorizontalBox {
                        new_class := LineEdit {
                            placeholder-text: "New class";
                        }

                        Button {
                            text: "Add";
                            clicked => {
                                root.add-class(new_class.text);
                                new_class.text = "";
                                root.is_saved = false;
                            };
                        }
                    }
                }
            }

            // Dialogue State
            Rectangle {
                width: 20%;

                VerticalBox {

                    LineEdit {
                        placeholder-text: "Search...";
                        accepted(text) => {
                            search("", text);
                        }
                    }

                    TouchArea {
                        // Unselect when click outside
                        // clicked => {
                        //      root.selecting_state = -1;
                        // }

                        ListView {
                            for state_name[i] in states: EditableTextBox {
                                value: state_name;
                                selected: {
                                    root.selecting_state == i
                                };
                                background: {
                                    if (root.selecting_state == i) {
                                        Palette.selection-background
                                    } else {
                                        Palette.background
                                    }
                                };
                                select => {
                                    select-state(state_name);
                                    root.selecting_state = i;
                                    root.selecting_dialog = -1;
                                };
                                submit(new_name) => {
                                    rename-state(state_name, new_name);
                                    root.is_saved = false;
                                };
                                delete => {
                                    remove-state(state_name);
                                    root.is_saved = false;
                                };
                            }
                        }
                    }

                    HorizontalBox {
                        visible: {
                            root.selecting_class >= 0
                        };
                        new_state := LineEdit {
                            placeholder-text: "New state";
                        }

                        Button {
                            text: "Add";
                            clicked => {
                                root.add-state(new_state.text);
                                root.is_saved = false;
                                new_state.text = "";
                            }
                        }
                    }
                }
            }

            // Dialogue list
            Rectangle {
                width: 20%;

                VerticalBox {

                    // Just to keep consistent position with other columns
                LineEdit {
                        placeholder-text: "Search...";
                        visible: false;
                    }

                    TouchArea {
                        clicked => {
                        // root.selecting_dialog = -1;
                        }

                        ListView {
                            for dialog[i] in dialogues: SelectableBox {
                                value: dialog;
                                selected: {
                                    root.selecting_dialog == i
                                };
                                background: {
                                    if (root.selecting_dialog == i) {
                                        Palette.selection-background
                                    } else {
                                        Palette.background
                                    }
                                };
                                select => {
                                    select-dialog(i);
                                    root.selecting_dialog = i;
                                };
                                delete_dialog => {
                                    remove-dialog(i);
                                    root.is_saved = false;
                                };
                            }
                        }
                    }

                    Button {
                        visible: {
                            root.selecting_state >= 0
                        };
                        text: "Add";
                        clicked => {
                            root.add-dialog();
                            root.is_saved = false;
                        }
                    }
                }
            }

            // Dialog detail
            Rectangle {
                VerticalBox {
                    DialogueBox {
                        visible: {
                            root.selecting_dialog >= 0
                        };
                        dialogue: dialogue;
                        lang_list: lang_list;
                        class_list: classes;
                        state_list: state_list;

                        update_content => {
                            root.update_content(self.dialogue);
                            root.is_saved = false;
                        };
                        new_lang_content(lang, content) => {
                            root.new_lang_content(lang, content);
                            root.is_saved = false;
                        };
                        new_affect(class, state) => {
                            root.new_affect(class, state);
                            root.is_saved = false;
                        };
                        delete_content(lang) => {
                            root.delete_content(lang);
                            root.is_saved = false;
                        }
                        delete_affect(class) => {
                            root.delete_affect(class);
                            root.is_saved = false;
                        }
                    }
                }
            }
        }

        VerticalLayout {
            height: 10%;
            HorizontalBox {
                file_path_input := LineEdit {
                    text: root.file_path;
                }

                Button {
                    text: "Browse";
                    clicked => {
                        file_picker();
                    }
                }
            }

            HorizontalBox {
                ui_file_format := ComboBox {
                    width: 80px;
                    model: ["RON", "BIN"];
                    current-index: file_format; // FIXME: If this is manual changed from UI, it can't be changed from backend anymore
                }

                ui_encrypt_key := LineEdit {
                    text: encrypt_key;
                    visible: enable_crypt;
                    placeholder-text: "Encryption key";
                }
            }

            HorizontalBox {
                Button {
                    text: "Load";
                    clicked => {
                        root.request-load(file_path_input.text, ui_file_format.current-index, ui_encrypt_key.text);
                    }
                }

                Button {
                    text: "Save";
                    clicked => {
                        root.request-save(file_path_input.text, ui_file_format.current-index, ui_encrypt_key.text);
                    }
                }
            }
        }

        StatusBar {
            height: 24px;
            is_saved: root.is_saved;
        }
    }
}
