import {
    TextEdit,
    Button,
    ListView,
    ComboBox,
    LineEdit,
    Palette,
    TabWidget,
} from "std-widgets.slint";
import {
    EditableTextBox,
    SelectableBox,
} from "app_widgets.slint";
import { StatusBar } from "status_bar.slint";
import { FileSection, GFile, UnsaveLoadDialog } from "file_section.slint";
import { NotiBox, GNoti } from "noti.slint";
import { StringId, GNameMap, NameMapTab } from "namemap_tab.slint";
import { ContentTab, GContent } from "content_tab.slint";
import { GSequence, SequenceTab } from "sequence_tab.slint";
import { ConfigTab } from "config_tab.slint";
import { GConfig } from "common.slint";
import {
    Vertical,
    ElevatedButton,
    MaterialWindow,
    Horizontal,
    SnackBar,
} from "material-1.0/material.slint";

export { GNoti, GNameMap, GContent, GConfig, GFile, GSequence, UnsaveLoadDialog }
export component AppWindow inherits MaterialWindow {
    title: "Dialogue Editor";
    maximized: true;

    in-out property <bool> is_saved: true;
    in-out property <bool> undo_available: false;
    in-out property <bool> redo_available: false;
    callback undo();
    callback redo();

    forward-focus: my-key-handler;

    public function show_notification() {
        noti_box.show();
    }

    noti_box := NotiBox {
        x: parent.width - self.width - 20px;
        y: 20px;
    }

    // TODO: Fix focus does not receive key press from child component
    my-key-handler := FocusScope {
        KeyBinding {
            keys: @keys(Control + Z);
            activated => {
                if (undo_available) {
                    root.undo();
                    root.is_saved = false;
                }
            }
        }

        KeyBinding {
            keys: @keys(Control + Shift + Z);
            activated => {
                if (redo_available) {
                    root.redo();
                    root.is_saved = false;
                }
            }
        }

        KeyBinding {
            keys: @keys(Control + O);
            activated => {
                file_section.open();
            }
        }

        KeyBinding {
            keys: @keys(Control + S);
            activated => {
                file_section.save();
            }
        }

        KeyBinding {
            keys: @keys(Control + Shift + S);
            activated => {
                file_section.save_as();
            }
        }

        VerticalLayout {
            file_section := FileSection { }

            HorizontalLayout {
                HorizontalLayout {
                    alignment: start;

                    Rectangle {
                        ElevatedButton {
                            visible: undo_available;
                            text: "Undo";
                            clicked => {
                                root.undo();
                                is_saved = false;
                            }
                            tooltip: "Ctrl + Z";
                        }
                    }

                    Rectangle {
                        ElevatedButton {
                            visible: redo_available;
                            text: "Redo";
                            clicked => {
                                root.redo();
                                is_saved = false;
                            }
                            tooltip: "Ctrl + Shift + Z";
                        }
                    }
                }

                Rectangle {
                    ElevatedButton {
                        text: "Refresh";
                        clicked => {
                            GContent.refresh();
                            GNameMap.refresh();
                        }
                    }
                }
            }

            TabWidget {
                orientation: Orientation.horizontal;

                Tab {
                    title: "Content";

                    ContentTab {
                        is_saved <=> root.is_saved;
                    }
                }

                Tab {
                    title: "Sequence";

                    SequenceTab {
                        is_saved <=> root.is_saved;
                    }
                }

                Tab {
                    title: "Namemap";

                    NameMapTab {
                        is_saved <=> root.is_saved;
                    }
                }

                Tab {
                    title: "Config";

                    ConfigTab { }
                }
            }

            StatusBar {
                is_saved <=> root.is_saved;
            }
        }
    }
}
