import {
    HorizontalBox,
    Button,
    VerticalBox,
    ComboBox,
    TextEdit,
} from "std-widgets.slint";

export struct UiDialogue {
    contents: [{ content: string, language: string}],
    affects: [{ class: string, state: string}],
}

export component DialogueBox inherits Rectangle {
    in-out property <UiDialogue> dialogue;
    in property <[string]> lang_list;
    in property <[string]> class_list;
    in property <[string]> state_list;

    callback new_lang_content(string, string);
    callback new_affect(string, string);
    callback update_content();

    outer := VerticalBox {
        for dialog[i] in dialogue.contents: HorizontalBox {
            ComboBox {
                model: lang_list;
                current-value: dialog.language;
                selected(current-value) => {
                    root.dialogue.contents[i].language = current-value;
                    submit_btn.visible = true;
                }
            }

            TextEdit {
                text: dialog.content;
                edited(value) => {
                    root.dialogue.contents[i].content = value;
                    submit_btn.visible = true;
                }
            }
        }
        new_lang := ComboBox {
            model: lang_list;
        }

        new_content := TextEdit { }

        Button {
            text: "Add";
            clicked => {
                update_content();
                new_lang_content(new_lang.current-value, new_content.text);
            };
        }

        for affect[i] in dialogue.affects: HorizontalBox {
            ComboBox {
                model: class_list;
                current-value: affect.class;
                selected(current-value) => {
                    dialogue.affects[i].class = current-value;
                    submit_btn.visible = true;
                }
            }

            ComboBox {
                // TODO: Filter state by class
                model: state_list;
                current-value: affect.state;
                selected(current-value) => {
                    dialogue.affects[i].state = current-value;
                    submit_btn.visible = true;
                }
            }
        }
        new_affect_class := ComboBox {
            model: class_list;
        }

        new_affect_state := ComboBox {
            model: state_list;
        }

        Button {
            text: "Add";
            clicked => {
                update_content();
                new_affect(new_affect_class.current-value, new_affect_state.current-value);
            };
        }

        submit_btn := Button {
            text: "Submit";
            clicked => {
                root.update_content();
                self.visible = false;
            };
        }
    }
}

export component SelectableBox inherits Rectangle {
    in property <string> value;
    callback delete();
    callback select();

    border-width: 1px;
    border-color: #ffffff;
    border-radius: 5px;

    TouchArea {
        width: 100%;
        height: 100%;

        clicked => {
            del_btn.visible = true;
            select();
        }

        Text {
            text: value;
        }

        del_btn := Button {
            text: "Delete";
            visible: false;
            clicked => {
                delete();
            };
        }
    }
}


export component EditableTextBox inherits Rectangle {
    in property <string> value;
    callback submit(string);
    callback delete();
    callback select;

    public function unfocus() {
        touch_area.unfocus();
    }

    border-width: 1px;
    border-color: #ffffff;
    border-radius: 5px;

    touch_area := TouchArea {
        width: 100%;
        height: 100%;

        function unfocus() {
            edit.read-only = true;
            edit.clear-focus();
            save_btn.visible = false;
            del_btn.visible = false;
        }

        clicked => {
            edit.read-only = false;
            edit.focus();
            save_btn.visible = true;
            del_btn.visible = true;
            select();
        }

        HorizontalBox {
            edit := TextInput {
                text: value;
                read-only: true;
            }

            save_btn := Button {
                text: "Accept";
                visible: false;
                clicked => {
                    submit(edit.text);
                }
            }

            del_btn := Button {
                text: "Delete";
                visible: false;
                clicked => {
                    delete();
                }
            }
        }
    }
}
