import {
    Button,
    ComboBox,
    TextEdit,
    LineEdit,
    ListView,
    Palette,
    ScrollView,
    VerticalBox,
    HorizontalBox,
} from "std-widgets.slint";
import {
    IconButton,
    Horizontal,
    Vertical,
    ElevatedCard,
} from "material-1.0/material.slint";
import { SearchBar } from "material-1.0/ui/components/search_bar.slint";
import { Icons } from "material-1.0/ui/icons/icons.slint";

export component TabReload inherits Rectangle { }

export component SelectableBox inherits ElevatedCard {
    in property <string> value;
    in property <bool> selected;

    callback delete();
    callback select();

    TouchArea {
        width: 100%;
        height: 100%;

        clicked => {
            select();
        }

        Horizontal {
            Text {
                text: {
                    if (value == "") {
                        return "New";
                    } else {
                        return value;
                    }
                };
            }

            del_btn := IconButton {
                icon: Icons.remove;
                visible: selected;
                clicked => {
                    delete();
                };
            }
        }
    }
}


export component EditableTextBox inherits ElevatedCard {
    in property <string> value;
    in-out property <bool> selected;
    private property <bool> is_edited: false;

    callback submit(string);
    callback delete();
    callback select;

    touch_area := TouchArea {
        width: 100%;
        height: 100%;

        clicked => {
            select();
        }

        Horizontal {
            edit := LineEdit {
                text: value;
                enabled: selected;
                read-only: !selected;

                accepted(text) => {
                    submit(self.text);
                    is_edited = false;
                }

                edited(text) => {
                    is_edited = true;
                }
            }

            if (root.is_edited): IconButton {
                icon: Icons.check;
                tooltip: "Submit";
                inline: true;

                clicked => {
                    submit(edit.text);
                    is_edited = false;
                }
            }

            del_btn := IconButton {
                icon: Icons.remove;
                visible: selected;
                tooltip: "Remove";
                inline: true;

                clicked => {
                    delete();
                    selected = false;
                }
            }
        }
    }
}

export component SearchBox inherits ElevatedCard {
    callback search(string);
    LineEdit {
        width: 100%;
        height: 100%;
        placeholder-text: "Search...";
        edited(text) => { search(text); }
        accepted(text) => { search(text); }
    }
}

export component SelectionBox inherits Rectangle {
    in property <[string]> items: [];
    in property <[string]> filtered-items: items;  // Override with parent's filtered list
    in property <string> placeholder-text: "Select or search...";
    in property <length> dropdown-max-height: 480px;
    out property <string> text;

    callback filter(string);
    callback accepted(string);

    VerticalBox {
        spacing: 4px;

        // Input field
        input-field := LineEdit {
            placeholder-text: root.placeholder-text;

            edited(text) => {
                search_popup.show();
                root.filter(text);
            }

            accepted(text) => {
                self.clear-focus();
                search_popup.close();
                root.accepted(self.text);
            }
        }

        // Dropdown list
        search_popup := PopupWindow {
            width: 160px;
            height: 240px;
            y: input-field.height + 4px;

            Rectangle {
                background: Palette.background;
                border-color: Palette.border;
                border-width: 1px;
                clip: false;
                max-height: root.dropdown-max-height;
                width: 100%;

                ListView {
                    for item in root.filtered-items: Rectangle {
                        background: item-touch.has-hover ?
                            Palette.accent-background : transparent;
                        border-radius: 2px;
                        height: 32px;

                        Rectangle {
                            width: 100%;
                            height: 100%;

                            Text {
                                text: item;
                                vertical-alignment: center;
                                x: 8px;
                                color: Palette.foreground;
                            }
                        }

                        item-touch := TouchArea {
                            width: 100%;
                            height: 100%;

                            clicked => {
                                input-field.text = item;
                                root.text = item;
                            }
                        }
                    }
                }
            }
        }
    }
}
