
import { TabReload, TagChip, SimpleTag, AddButton } from "app_widgets.slint";
import {
    Palette,
    Button,
    LineEdit,
    ListView,
    CheckBox,
    Slider,
    ScrollView,
    HorizontalBox,
    VerticalBox,
    GridBox,
    Switch,
} from "std-widgets.slint";
import { GFile } from "file_section.slint";
import { GConfig } from "common.slint";

export component Tag inherits Rectangle {
    in property <string> value;
    callback delete();

    HorizontalBox {
        Text {
            text <=> value;
        }

        Button {
            text: "x";
            clicked => {
                delete();
            }
        }
    }
}

export component ConfigTab inherits TabReload {
    VerticalBox {
        alignment: start;

        VerticalBox {
            HorizontalBox {
                alignment: start;

                Image {
                    source: @image-url("icons/localization_icon.svg");
                }

                Text {
                    text: "LANGUAGE SETTINGS";
                    font-size: 15px;
                    font-weight: 700;
                }
            }

            VerticalBox {
                Text {
                    text: "SUPPORTED LANGUAGES";
                    font-size: 12px;
                    color: #a1a1aa;
                    font-weight: 700;
                }

                Rectangle {
                    background: #18181b;
                    border-radius: 6px;
                    border-width: 1px;
                    border-color: #2f2f37;

                    HorizontalBox {
                        for lang[i] in GConfig.lang_list: SimpleTag {
                            text: lang;
                            text-color: #f97316;
                            font-size: 13px;
                            font-weight: 700;
                            icon: @image-url("icons/x_circle.svg");
                            btn_tooltip: @markdown("Remove");

                            btn_clicked => {
                                GConfig.delete_lang(lang);
                            }
                        }
                    }
                }
            }

            HorizontalBox {
                new_lang := LineEdit {
                    placeholder-text: "Language code, separated by space";
                }

                AddButton {
                    width: 80px;
                    clicked => {
                        GConfig.add_lang(new_lang.text);
                        new_lang.text = "";
                    }
                }
            }
        }

        VerticalBox {
            HorizontalBox {
                alignment: start;

                Image {
                    source: @image-url("icons/save_icon.svg");
                }

                Text {
                    text: "EXPORT SETTINGS";
                    font-size: 15px;
                    font-weight: 700;
                }
            }

            HorizontalBox {
                alignment: start;

                Rectangle {
                    Switch {
                        checked <=> GConfig.save_without_namemap;
                        toggled => {
                            GConfig.set_save_without_namemap(self.checked);
                        }
                    }
                }

                Text {
                    text: "Save dialogue without name map";
                    font-size: 14px;
                    font-weight: 700;
                }
            }

            if (GFile.enable_crypt): Rectangle {
                LineEdit {
                    text <=> GFile.encrypt_key;
                    placeholder-text: "Encryption key";
                }
            }
        }

        VerticalBox {
            HorizontalBox {
                alignment: start;

                Image {
                    source: @image-url("icons/gear_icon.svg");
                }

                Text {
                    text: "EDITOR SETTINGS";
                    font-size: 15px;
                    font-weight: 700;
                }
            }

            Text {
                text: "MAXIMUM UNDO STEPS";
                font-size: 12px;
                color: #a1a1aa;
                font-weight: 700;
            }

            HorizontalBox {
                alignment: start;
                cross-axis-alignment: center;

                max_undo := LineEdit {
                    text: GConfig.max_undo;
                    input-type: number;
                    accepted(text) => {
                        GConfig.max_undo = self.text.to-float().round();
                        GConfig.set_max_undo(GConfig.max_undo);
                    }
                }

                Rectangle {
                    background: #27272a;
                    border-radius: 6px;
                    border-width: 1px;
                    border-color: #3f3f46;
                    Button {
                        text: "Set";
                        clicked => {
                            max_undo.accepted(max_undo.text);
                        }
                    }
                }

                Text {
                    text: "0 means unlimited";
                    font-size: 12px;
                    font-weight: 400;
                    color: #717680;
                }
            }

            Text {
                text: "AUTOSAVE";
                font-size: 12px;
                color: #a1a1aa;
                font-weight: 700;
            }

            HorizontalBox {
                alignment: start;
                cross-axis-alignment: center;

                Text {
                    text: "Every";
                    color: #a1a1aa;
                    font-size: 12px;
                    font-weight: 400;
                }

                autosave_interval := LineEdit {
                    text: GConfig.autosave_interval;
                    input-type: number;
                    accepted(text) => {
                        GConfig.autosave_interval = self.text.to-float().round();
                        GConfig.set_autosave_interval(GConfig.autosave_interval);
                    }
                }

                Text {
                    text: "seconds";
                    color: #a1a1aa;
                    font-size: 12px;
                    font-weight: 400;
                }

                Rectangle {
                    background: #27272a;
                    border-radius: 6px;
                    border-width: 1px;
                    border-color: #3f3f46;
                    Button {
                        text: "Set";
                        clicked => {
                            autosave_interval.accepted(autosave_interval.text);
                        }
                    }
                }

                Text {
                    text: "0 means disabled";
                    font-size: 12px;
                    font-weight: 400;
                    color: #717680;
                }
            }
        }
    }
}
