
import { TabReload } from "app_widgets.slint";
import {
    Palette,
    Button,
    LineEdit,
    ListView,
    CheckBox,
} from "std-widgets.slint";
import {
    Horizontal,
    Vertical,
    ElevatedButton,
    InputChip,
    OutlinedCard,
    Grid,
    HorizontalDivider,
    Switch,
} from "material-1.0/material.slint";
import { GFile } from "file_section.slint";
import { Icons } from "material-1.0/ui/icons/icons.slint";
import { GConfig } from "common.slint";

export component Tag inherits Rectangle {
    in property <string> value;
    callback delete();

    Horizontal {
        Text {
            text <=> value;
        }

        Button {
            text: "x";
            clicked => {
                delete();
            }
        }
    }
}

export component ConfigTab inherits TabReload {
    Vertical {
        Rectangle {
            Horizontal {
                Text {
                    text: "Save dialogue without name map";
                }

                Rectangle {
                    Switch {
                        checked <=> GFile.save_without_name;
                    }
                }
            }
        }

        if (GFile.enable_crypt):
        Rectangle {
            LineEdit {
                text <=> GFile.encrypt_key;
                placeholder-text: "Encryption key";
            }
        }

        HorizontalDivider { }

        Rectangle {
            Vertical {
                alignment: start;

                Text {
                    text: "Dialogue languages";
                }

                Rectangle {
                    Horizontal {
                        alignment: start;
                        for lang[i] in GConfig.lang_list: Rectangle {
                            InputChip {
                                text: lang;
                                trailing_icon: Icons.close;
                                trailing_icon_clicked => {
                                    GConfig.delete_lang(lang);
                                }
                            }
                        }
                    }
                }

                Rectangle {
                    Horizontal {
                        new_lang := LineEdit {
                            placeholder-text: "Language code in ISO-639-3";
                        }

                        ElevatedButton {
                            text: "Add";
                            clicked => {
                                GConfig.add_lang(new_lang.text);
                                self.text = "";
                            }
                        }
                    }
                }
            }
        }
    }
}
