
import { TabReload } from "app_widgets.slint";
import {
    Palette,
    Button,
    LineEdit,
    ListView,
    CheckBox,
    ScrollView,
} from "std-widgets.slint";
import {
    Horizontal,
    Vertical,
    ElevatedButton,
    InputChip,
    OutlinedCard,
    Grid,
    Slider,
    HorizontalDivider,
    Switch,
} from "material-1.0/material.slint";
import { GFile } from "file_section.slint";
import { Icons } from "material-1.0/ui/icons/icons.slint";
import { GConfig } from "common.slint";

export component Tag inherits Rectangle {
    in property <string> value;
    callback delete();

    Horizontal {
        Text {
            text <=> value;
        }

        Button {
            text: "x";
            clicked => {
                delete();
            }
        }
    }
}

export component ConfigTab inherits TabReload {
    ScrollView {
        Vertical {
            Vertical {
                alignment: start;

                Text {
                    text: "Dialogue languages";
                }

                Grid {
                    for lang[i] in GConfig.lang_list: Rectangle {
                        row: i / 9;
                        col: Math.mod(i, 9);

                        InputChip {
                            text: lang;
                            trailing_icon: Icons.close;
                            trailing_icon_clicked => {
                                GConfig.delete_lang(lang);
                            }
                        }
                    }
                }

                Horizontal {
                    new_lang := LineEdit {
                        placeholder-text: "Language code in ISO-639 (separate by space)";
                    }

                    ElevatedButton {
                        text: "Add";
                        clicked => {
                            GConfig.add_lang(new_lang.text);
                            self.text = "";
                        }
                    }
                }
            }

            HorizontalDivider { }

            Horizontal {
                Text {
                    text: "Save dialogue without name map";
                }

                Rectangle {
                    Switch {
                        checked <=> GFile.save_without_name;
                    }
                }
            }

            Horizontal {
                Text {
                    text: "Maximum undo: " + GConfig.max_undo;
                }

                Slider {
                    value: GConfig.max_undo;
                    minimum: 10;
                    maximum: 100;
                    stop-count: 1;
                    released(value) => {
                        GConfig.set_max_undo(value.round());
                    }
                }
            }

            if (GFile.enable_crypt): Rectangle {
                LineEdit {
                    text <=> GFile.encrypt_key;
                    placeholder-text: "Encryption key";
                }
            }
        }
    }
}
