import {
    TabReload,
    EditableTextBox,
    SelectableBox,
    SearchBox,
    SelectionBox,
    EditButton,
    DeleteButton,
    ColumnTitle,
    AddButton,
    TagChip,
    AddText,
} from "app_widgets.slint";
import {
    Palette,
    LineEdit,
    ListView,
    Button,
    ComboBox,
    TextEdit,
    HorizontalBox,
    VerticalBox,
    ScrollView,
    GridBox,
} from "std-widgets.slint";
import { VerticalDivider } from "material-1.0/ui/components/divider.slint";
import { GConfig } from "common.slint";


export struct ContentLang {
    language: string,
    content: string,
}

export struct Affect {
    class: string,
    state: string,
}

export struct UiDialogue {
    contents: [ContentLang],
    affects: [Affect],
    events: [string],
}

export global GContent {
    in-out property <[string]> classes;
    in-out property <[string]> states;
    in-out property <[string]> dialogues;
    in-out property <UiDialogue> dialogue;

    // Used for dialogue affect and event selection
    in-out property <[string]> class_list;
    in-out property <[string]> state_list;
    in-out property <[string]> event_list;

    in-out property <string> selecting_class: "";
    in-out property <string> selecting_state: "";
    in-out property <int> selecting_dialogue: -1;

    callback refresh();

    callback select-class(string);
    callback remove-class(string);
    callback add-class(string);
    callback rename-class(string, string); // old name, new name

    callback select-state(string);
    callback remove-state(string);
    callback add-state(string);
    callback rename-state(string, string); // old name, new name

    callback select-dialog(int);
    callback add-dialog();
    callback remove-dialog(int);

    callback add_lang_content(string, string); // lang, content
    callback add_affect(string, string); // affect_class, affect_state
    callback add_event(string);
    callback update_content(string, string);
    callback delete_content(string);
    callback delete_affect(string);
    callback delete_event(string);

    callback search_class(string);
    callback search_state(string);
    callback search_dialogue(string);
    callback search_event(string);
    callback search_affect_class(string);
    callback search_affect_state(string, string);

    callback goto(string, string);
}

export component DialogueBox inherits Rectangle {
    property <int> content_selecting;
    property <bool> is_edited: false;

    VerticalBox {
        VerticalBox {
            height: 50%;

            Text {
                text: "CONTENT";
                font-size: 14px;
                font-weight: 700;
            }

            ListView {
                for dialog[i] in GContent.dialogue.contents: HorizontalBox {
                    alignment: LayoutAlignment.stretch;
                    cross-axis-alignment: center;

                    VerticalBox {
                        Rectangle {
                            background: #2a2a2b;
                            border-radius: 4px;
                            border-width: 1px;
                            border-color: #38383a;
                            width: 44px;
                            height: 22px;

                            Text {
                                color: #f59e0b;
                                text: dialog.language;
                                font-size: 12px;
                                font-weight: 600;
                            }
                        }
                    }

                    content_view := TextEdit {
                        height: 72px;
                        text: dialog.content;
                        edited(value) => {
                            GContent.dialogue.contents[i].content = value;
                            is_edited = true;
                        }
                    }

                    VerticalBox {
                        EditButton {
                            visible: is_edited;
                            clicked => {
                                GContent.update_content(dialog.language, content_view.text);
                                is_edited = false;
                            }
                        }

                        DeleteButton {
                            clicked => {
                                GContent.delete_content(dialog.language);
                                is_edited = false;
                            }
                        }
                    }
                }
            }

            Rectangle {
                background: #222223;
                border-radius: 6px;
                border-width: 1px;
                border-color: #2d2d2f;
                width: 100%;

                HorizontalBox {
                    cross-axis-alignment: center;
                    alignment: stretch;

                    new_lang := ComboBox {
                        width: 72px;
                        model: GConfig.lang_list;
                        current-index: 0;
                    }

                    new_content := LineEdit {
                        placeholder-text: "new dialog";
                    }

                    AddButton {
                        width: 48px;
                        clicked => {
                            GContent.add_lang_content(new_lang.current-value, new_content.text);
                            new_content.text = "";
                            is_edited = false;
                        };
                    }
                }
            }
        }

        VerticalBox {
            Text {
                text: "STATE AFFECT";
                font-size: 14px;
                font-weight: 700;
            }

            GridBox {
                for affect[i] in GContent.dialogue.affects: TagChip {
                    row: i / 3;
                    col: Math.mod(i, 3);

                    TouchArea {
                        clicked => { GContent.goto(affect.class, affect.state); }

                        HorizontalBox {
                            cross-axis-alignment: center;
                            alignment: space-between;

                            HorizontalBox {
                                cross-axis-alignment: center;

                                Text {
                                    text: affect.class;
                                    font-size: 12px;
                                    font-weight: 400;
                                    color: #a3a3a8;
                                }

                                Image {
                                    source: @image-url("icons/arrow_right.svg");
                                }

                                Text {
                                    text: affect.state;
                                    font-size: 12px;
                                    font-weight: 600;
                                    color: #8b5cf6;
                                }
                            }

                            TouchArea {
                                clicked => {
                                    GContent.delete_affect(affect.class);
                                }

                                Image {
                                    source: @image-url("icons/x_circle.svg");
                                }
                            }
                        }
                    }
                }
            }

            Rectangle {
                width: 100%;
                background: #222223;
                border-radius: 6px;
                border-width: 1px;
                border-color: #2d2d2f;

                HorizontalBox {
                    cross-axis-alignment: center;

                    new_affect_class := SelectionBox {
                        items: GContent.class_list;
                        placeholder-text: "Target";
                        filter(text) => {
                            GContent.search_affect_class(text);
                        }
                    }

                    new_affect_state := SelectionBox {
                        items: GContent.state_list;
                        placeholder-text: "Become";
                        filter(text) => {
                            GContent.search_affect_state(new_affect_class.text, text);
                        }
                    }

                    AddButton {
                        width: 48px;
                        clicked => {
                            GContent.add_affect(new_affect_class.text, new_affect_state.text);
                            new_affect_class.clear();
                            new_affect_state.clear();
                        };
                    }
                }
            }
        }

        VerticalBox {
            Text {
                text: "EVENTS";
                font-size: 14px;
                font-weight: 700;
            }

            HorizontalBox {
                new_event := SelectionBox {
                    items: GContent.event_list;
                    filter(text) => {
                        GContent.search_event(text);
                    }
                }

                Rectangle {
                    AddButton {
                        text: "Add Trigger";
                        clicked => {
                            GContent.add_event(new_event.text);
                            new_event.clear();
                        };
                    }
                }
            }

            ScrollView {
                GridBox {
                    for event[i] in GContent.dialogue.events: TagChip {
                        row: i / 3;
                        col: Math.mod(i, 3);

                        TouchArea {
                            width: 100%;
                            height: 100%;

                            HorizontalBox {
                                alignment: space-between;
                                cross-axis-alignment: center;

                                Text {
                                    text: event;
                                    color: #10b981;
                                    font-size: 12px;
                                    font-weight: 600;
                                }

                                Rectangle {
                                    Button {
                                        clicked => {
                                            GContent.delete_event(event);
                                        }
                                    }

                                    Image {
                                        source: @image-url("icons/x_circle.svg");
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

export component ContentTab inherits TabReload {
    in-out property <bool> is_saved;

    HorizontalBox {
        // TODO: Allow resizeable
        alignment: stretch;

        Rectangle {
            width: 15%;

            VerticalBox {
                ColumnTitle {
                    title: "Class";
                    count: GContent.classes.length;
                }

                SearchBox {
                    search(text) => {
                        GContent.search_class(text);
                        GContent.selecting_class = "";
                        GContent.selecting_state = "";
                        GContent.selecting_dialogue = -1;
                    }
                }

                // TODO: highlight selected item
                ListView {
                    for class_name[i] in GContent.classes: EditableTextBox {
                        value: class_name;
                        selected: {
                            GContent.selecting_class == class_name
                        };
                        // background: {
                        //     if (GContent.selecting_class == class_name) {
                        //         Palette.selection-background
                        //     } else {
                        //         Palette.background
                        //     }
                        // };
                        select => {
                            GContent.select-class(class_name);
                            GContent.selecting_class = class_name;
                            GContent.selecting_state = "";
                            GContent.selecting_dialogue = -1;
                        };
                        submit(new_name) => {
                            GContent.rename-class(class_name, new_name);
                            root.is_saved = false;
                        };
                        delete => {
                            GContent.remove-class(class_name);
                            root.is_saved = false;
                        };
                    }
                }

                AddText {
                    placeholder: "New class";
                    add(text) => {
                        GContent.add-class(text);
                        root.is_saved = false;
                    }
                }
            }
        }

        VerticalDivider { }

        Rectangle {
            width: 15%;

            VerticalBox {
                ColumnTitle {
                    title: "State";
                    count: GContent.states.length;
                }

                SearchBox {
                    search(text) => {
                        GContent.search_state(text);
                        GContent.selecting_state = "";
                        GContent.selecting_dialogue = -1;
                    }
                }

                ListView {
                    // TODO: Allow state to be reordered
                    for state_name[i] in GContent.states: EditableTextBox {
                        value: state_name;
                        selected: {
                            GContent.selecting_state == state_name
                        };
                        // background: {
                        //     if (GContent.selecting_state == state_name) {
                        //         Palette.selection-background
                        //     } else {
                        //         Palette.background
                        //     }
                        // };
                        select => {
                            GContent.select-state(state_name);
                            GContent.selecting_state = state_name;
                            GContent.selecting_dialogue = -1;
                        };
                        submit(new_name) => {
                            GContent.rename-state(state_name, new_name);
                            root.is_saved = false;
                        };
                        delete => {
                            GContent.remove-state(state_name);
                            root.is_saved = false;
                        };
                    }
                }

                Rectangle {
                    visible: {
                        GContent.selecting_class != "" || GContent.selecting_state != ""
                    };

                    AddText {
                        placeholder: "New state";
                        add(text) => { GContent.add-state(text); root.is_saved = false; }
                    }
                }
            }
        }

        VerticalDivider { }

        Rectangle {
            width: 20%;

            VerticalBox {
                ColumnTitle {
                    title: "Dialogue";
                    count: GContent.dialogues.length;
                }

                SearchBox {
                    search(text) => {
                        GContent.search_dialogue(text);
                        GContent.selecting_dialogue = -1;
                    }
                }

                ListView {
                    for dialog[i] in GContent.dialogues: SelectableBox {
                        value: dialog;
                        selected: {
                            GContent.selecting_dialogue == i
                        };

                        select => {
                            GContent.select-dialog(i);
                            GContent.selecting_dialogue = i;
                        };
                        delete => {
                            GContent.remove-dialog(i);
                            root.is_saved = false;
                        };
                    }
                }

                AddButton {
                    visible: {
                        GContent.selecting_state != ""
                    };
                    clicked => {
                        GContent.add-dialog();
                        root.is_saved = false;
                    }
                }
            }
        }

        VerticalDivider { }

        DialogueBox {
            width: 45%;
            visible: {
                GContent.selecting_dialogue >= 0
            };
        }
    }
}
