import {
    TabReload,
    EditableTextBox,
    SelectableBox,
    SearchBox,
    SelectionBox,
} from "app_widgets.slint";
import {
    Palette,
    LineEdit,
    ListView,
    Button,
    ComboBox,
    TextEdit,
    HorizontalBox,
    VerticalBox,
    ScrollView,
} from "std-widgets.slint";
import {
    Vertical,
    Horizontal,
    OutlinedCard,
    ElevatedCard,
    IconButton,
    TextButton,
    FilledCard,
    ElevatedButton,
    HorizontalDivider,
    FloatingActionButton,
    InputChip,
} from "material-1.0/material.slint";
import { Icons } from "material-1.0/ui/icons/icons.slint";
import { VerticalDivider } from "material-1.0/ui/components/divider.slint";
import { GConfig } from "common.slint";
import { ListItem, Grid } from "material-1.0/material.slint";
import { SearchBar } from "material-1.0/ui/components/search_bar.slint";


export struct ContentLang {
    language: string,
    content: string,
}

export struct Affect {
    class: string,
    state: string,
}

export struct UiDialogue {
    contents: [ContentLang],
    affects: [Affect],
    events: [string],
}

export global GContent {
    in-out property <[string]> classes;
    in-out property <[string]> states;
    in-out property <[string]> dialogues;
    in-out property <UiDialogue> dialogue;

    // Used for dialogue affect and event selection
    in-out property <[ListItem]> class_list;
    in-out property <[ListItem]> state_list;
    in-out property <[string]> event_list;

    in-out property <string> selecting_class: "";
    in-out property <string> selecting_state: "";
    in-out property <int> selecting_dialogue: -1;

    callback refresh();

    callback select-class(string);
    callback remove-class(string);
    callback add-class(string);
    callback rename-class(string, string); // old name, new name

    callback select-state(string);
    callback remove-state(string);
    callback add-state(string);
    callback rename-state(string, string); // old name, new name

    callback select-dialog(int);
    callback add-dialog();
    callback remove-dialog(int);

    callback add_lang_content(string, string); // lang, content
    callback add_affect(string, string); // affect_class, affect_state
    callback add_event(string);
    callback update_content(string, string);
    callback delete_content(string);
    callback delete_affect(string);
    callback delete_event(string);

    callback search_class(string);
    callback search_state(string);
    callback search_dialogue(string);
    callback search_event(string);

    callback goto(string, string);
}

export component DialogueBox inherits Rectangle {
    property <int> content_selecting;
    property <bool> is_edited: false;

    Vertical {
        Vertical {
            height: 50%;

            ListView {
                for dialog[i] in GContent.dialogue.contents: Horizontal {
                    alignment: start;
                    Vertical {
                        Text {
                            text: dialog.language;
                        }

                        IconButton {
                            icon: Icons.check;
                            tooltip: "Submit";
                            visible: is_edited;
                            clicked => {
                                GContent.update_content(dialog.language, content_view.text);
                                is_edited = false;
                            }
                        }
                    }

                    content_view := TextEdit {
                        height: 96px;
                        width: 80%;
                        text: dialog.content;
                        edited(value) => {
                            GContent.dialogue.contents[i].content = value;
                            is_edited = true;
                        }
                    }

                    Rectangle {
                        IconButton {
                            icon: Icons.remove;
                            clicked => {
                                GContent.delete_content(dialog.language);
                                is_edited = false;
                            }
                        }
                    }
                }
            }

            Horizontal {
                alignment: start;
                Rectangle {
                    new_lang := ComboBox {
                        model: GConfig.lang_list;
                        current-index: 0;
                    }
                }

                new_content := LineEdit {
                    placeholder-text: "new dialog";
                }

                TextButton {
                    text: "Add";
                    clicked => {
                        GContent.add_lang_content(new_lang.current-value, new_content.text);
                        new_content.text = "";
                        is_edited = false;
                    };
                }
            }
        }

        HorizontalDivider { }

        Vertical {
            Text {
                text: "Affect list";
            }

            Grid {
                for affect[i] in GContent.dialogue.affects: Rectangle {
                    row: i / 2;
                    col: Math.mod(i, 2);
                    InputChip {
                        text: { affect.class + ":" + affect.state };
                        trailing_icon: Icons.remove;
                        trailing_icon_clicked => {
                            GContent.delete_affect(affect.class);
                        }
                        clicked => { GContent.goto(affect.class, affect.state); }
                    }
                }
            }

            Horizontal {
                new_affect_class := SearchBar {
                    items: GContent.class_list;
                }
                // TODO: Filter state by class
                new_affect_state := SearchBar {
                    items: GContent.state_list;
                }

                TextButton {
                    text: "Add";
                    clicked => {
                        GContent.add_affect(new_affect_class.text, new_affect_state.text);
                    };
                }
            }
        }

        HorizontalDivider { }

        Vertical {
            event_label := Text {
                text: "Event List";
            }

            Rectangle {
                HorizontalBox {
                    new_event := SelectionBox {
                        items: GContent.event_list;
                        filter(text) => {
                            GContent.search_event(text);
                        }
                        accepted(text) => {
                            GContent.add_event(text);
                        }
                    }

                    Rectangle {
                        new_event_btn := TextButton {
                            text: "Add";
                            clicked => {
                                GContent.add_event(new_event.text);
                            };
                        }
                    }
                }

                ScrollView {
                    y: new_event_btn.height + 10px;
                    Grid {
                        for event[i] in GContent.dialogue.events: Rectangle {
                            row: i / 2;
                            col: Math.mod(i, 2);
                            InputChip {
                                text: event;
                                trailing_icon: Icons.remove;
                                trailing_icon_clicked => {
                                    GContent.delete_event(event);
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

export component ContentTab inherits TabReload {
    in-out property <bool> is_saved;

    Horizontal {
        // TODO: Allow resizeable
        Rectangle {
            width: 15%;

            Vertical {
                SearchBox {
                    search(text) => {
                        GContent.search_class(text);
                        GContent.selecting_class = "";
                        GContent.selecting_state = "";
                        GContent.selecting_dialogue = -1;
                    }
                }

                ListView {
                    for class_name[i] in GContent.classes: EditableTextBox {
                        value: class_name;
                        selected: {
                            GContent.selecting_class == class_name
                        };
                        // background: {
                        //     if (GContent.selecting_class == class_name) {
                        //         Palette.selection-background
                        //     } else {
                        //         Palette.background
                        //     }
                        // };
                        select => {
                            GContent.select-class(class_name);
                            GContent.selecting_class = class_name;
                            GContent.selecting_state = "";
                            GContent.selecting_dialogue = -1;
                        };
                        submit(new_name) => {
                            GContent.rename-class(class_name, new_name);
                            root.is_saved = false;
                        };
                        delete => {
                            GContent.remove-class(class_name);
                            root.is_saved = false;
                        };
                    }
                }

                Horizontal {
                    new_class := LineEdit {
                        placeholder-text: "New class";
                        accepted(text) => {
                            GContent.add-class(new_class.text);
                            self.text = "";
                            root.is_saved = false;
                        }
                    }

                    ElevatedButton {
                        text: "Add";
                        clicked => {
                            new_class.accepted(new_class.text);
                        };
                    }
                }
            }
        }

        VerticalDivider { }

        Rectangle {
            width: 15%;

            Vertical {
                SearchBox {
                    search(text) => {
                        GContent.search_state(text);
                        GContent.selecting_state = "";
                        GContent.selecting_dialogue = -1;
                    }
                }

                ListView {
                    // TODO: Allow state to be reordered
                    for state_name[i] in GContent.states: EditableTextBox {
                        value: state_name;
                        selected: {
                            GContent.selecting_state == state_name
                        };
                        // background: {
                        //     if (GContent.selecting_state == state_name) {
                        //         Palette.selection-background
                        //     } else {
                        //         Palette.background
                        //     }
                        // };
                        select => {
                            GContent.select-state(state_name);
                            GContent.selecting_state = state_name;
                            GContent.selecting_dialogue = -1;
                        };
                        submit(new_name) => {
                            GContent.rename-state(state_name, new_name);
                            root.is_saved = false;
                        };
                        delete => {
                            GContent.remove-state(state_name);
                            root.is_saved = false;
                        };
                    }
                }

                Rectangle {
                    visible: {
                        GContent.selecting_class != "" || GContent.selecting_state != ""
                    };
                    Horizontal {
                        new_state := LineEdit {
                            placeholder-text: "New state";
                            accepted(text) => {
                                GContent.add-state(new_state.text);
                                root.is_saved = false;
                                self.text = "";
                            }
                        }

                        ElevatedButton {
                            text: "Add";
                            clicked => {
                                new_state.accepted(new_state.text);
                            }
                        }
                    }
                }
            }
        }

        VerticalDivider { }

        Rectangle {
            width: 20%;

            Vertical {
                SearchBox {
                    search(text) => {
                        GContent.search_dialogue(text);
                        GContent.selecting_dialogue = -1;
                    }
                }

                ListView {
                    for dialog[i] in GContent.dialogues: SelectableBox {
                        value: dialog;
                        selected: {
                            GContent.selecting_dialogue == i
                        };

                        select => {
                            GContent.select-dialog(i);
                            GContent.selecting_dialogue = i;
                        };
                        delete => {
                            GContent.remove-dialog(i);
                            root.is_saved = false;
                        };
                    }
                }

                ElevatedButton {
                    visible: {
                        GContent.selecting_state != ""
                    };
                    text: "Add";
                    clicked => {
                        GContent.add-dialog();
                        root.is_saved = false;
                    }
                }
            }
        }

        VerticalDivider { }

        Rectangle {
            DialogueBox {
                visible: {
                    GContent.selecting_dialogue >= 0
                };
            }
        }
    }
}
