
import {
    ComboBox,
    LineEdit,
    Button,
    CheckBox,
    Palette,
    StandardButton,
} from "std-widgets.slint";
import { Horizontal, Vertical } from "material-1.0/material.slint";
import { OutlinedCard } from "material-1.0/ui/components/card.slint";
import { ElevatedButton } from "material-1.0/ui/components/elevated_button.slint";
import { Icons } from "material-1.0/ui/icons/icons.slint";

export global GFile {
    in-out property <int> file_format;
    in-out property <bool> enable_crypt;
    in-out property <string> encrypt_key;
    in-out property <string> file_path;
    in-out property <bool> save_without_name;

    callback file_picker();
    callback load(string, int, string, bool);
    callback save(string, int, string, bool, bool);
}

export component UnsaveLoadDialog inherits Dialog {
    callback request-close();

    title: "Dialogue Editor - Unsave Warning";

    Text {
        text: "Your work has not been saved yet! Continue without Save?";
    }

    StandardButton {
        kind: yes;
    }

    StandardButton {
        kind: cancel;
    }
}

export component FileSection inherits OutlinedCard {
    Vertical {
        Horizontal {
            ui_file_format := ComboBox {
                width: 80px;
                model: ["RON", "BIN"];
                // FIXME: If this is manual changed from UI, it can't be changed from backend anymore
                current-index <=> GFile.file_format;
            }

            file_path_input := LineEdit {
                text <=> GFile.file_path;
            }

            ElevatedButton {
                text: "Browse";
                clicked => {
                    GFile.file_picker();
                }
            }
        }

        Horizontal {
            ui_encrypt_key := LineEdit {
                text <=> GFile.encrypt_key;
                visible <=> GFile.enable_crypt;
                height: {
                    if (GFile.enable_crypt) {
                        30%
                    } else {
                        0%
                    }
                };
                placeholder-text: "Encryption key";
            }

            save_without_name := CheckBox {
                text: "Save dialogue without name map";
                checked <=> GFile.save_without_name;
            }
        }

        Horizontal {
            ElevatedButton {
                text: "Load";
                clicked => {
                    GFile.load(GFile.file_path, GFile.file_format, GFile.encrypt_key, false);
                }
            }

            ElevatedButton {
                text: "Save";
                clicked => {
                    GFile.save(GFile.file_path, GFile.file_format, GFile.encrypt_key, GFile.save_without_name, false);
                }
            }
        }
    }
}
