import {
    ComboBox,
    LineEdit,
    Button,
    CheckBox,
    Palette,
    StandardButton,
} from "std-widgets.slint";
import { Horizontal, Vertical } from "material-1.0/material.slint";
import { OutlinedCard } from "material-1.0/ui/components/card.slint";
import {
    ElevatedButton,
} from "material-1.0/ui/components/elevated_button.slint";
import { Icons } from "material-1.0/ui/icons/icons.slint";
import { GContent } from "content_tab.slint";
import { GNameMap } from "namemap_tab.slint";

export global GFile {
    in-out property <int> file_format;
    in-out property <bool> enable_crypt;
    in-out property <string> encrypt_key;
    in-out property <string> file_path;
    in-out property <bool> save_without_name;

    // file_format, load_true_save_false
    callback file_picker(int, bool);
    callback load(string, int, string, bool);
    callback save(string, int, string, bool, bool);
}

export component UnsaveLoadDialog inherits Dialog {
    callback request-close();

    title: "Dialogue Editor - Unsave Warning";

    Text {
        text: "Your work has not been saved yet! Continue without Save?";
    }

    StandardButton {
        kind: yes;
    }

    StandardButton {
        kind: cancel;
    }
}

export component FileSection inherits Rectangle {

    Horizontal {
        ui_file_format := ComboBox {
            width: 80px;
            model: ["RON", "BIN"];
                // FIXME: If this is manual changed from UI, it can't be changed from backend anymore
                current-index <=> GFile.file_format;
        }

        file_path_input := LineEdit {
            text <=> GFile.file_path;
        }

        ElevatedButton {
            text: "Load";
            clicked => {
                GFile.file_picker(GFile.file_format, true);
            }
        }

        ElevatedButton {
            text: "Save";
            clicked => {
                if (GFile.file_path == "") {
                    GFile.file_picker(GFile.file_format, false);
                } else {
                    GFile.save(GFile.file_path, GFile.file_format, GFile.encrypt_key, GFile.save_without_name, false);
                }
            }
        }
    }
}
