import {
    HorizontalBox,
    VerticalBox,
    LineEdit,
    Button,
    GridBox,
    ScrollView,
    Palette,
    ListView,
} from "std-widgets.slint";
import { TabReload, EditableTextBox } from "app_widgets.slint";


export struct StringId {
    name: string,
    id: string, // Do not use int, since it is just i32 while we need id is u64
}

export global GNameMap {
    in-out property <[StringId]> classes;
    in-out property <[StringId]> states;
    in-out property <[StringId]> events;

    pure callback reload();
    callback delete_class(string);
    callback delete_state(string);
    callback delete_event(string);
    callback update_class_id(string, string); // name, id
    callback update_state_id(string, string);
    callback update_event_id(string, string);
    callback new_class(string, string); // name ,id
    callback new_state(string, string); // name ,id
    callback new_event(string, string); // name ,id
}


export component StringIdContainer inherits Rectangle {
    in-out property <[StringId]> values;

    callback delete(string);
    callback update(string, string); // name, id
    callback new(string, string);

    VerticalBox {
        ListView {
            for value[i] in values: HorizontalBox {
                // TODO: Allow rename
                Text {
                    text: value.name;
                }

                edit := LineEdit {
                    text: value.id;
                    input-type: number;
                    accepted(text) => {
                        update(value.name, self.text);
                    }
                }

                Button {
                    text: "";
                    clicked => {
                        update(value.name, edit.text);
                    }
                }

                Button {
                    text: "Del";
                    clicked => {
                        delete(value.name);
                    }
                }
            }
        }

        HorizontalBox {
            new_name := LineEdit {
                placeholder-text: "New name";

                accepted(text) => {
                    submit()
                }
            }

            new_id := LineEdit {
                placeholder-text: "New id";
                accepted(text) => {
                    submit()
                }
            }

            Button {
                text: "Add";
                clicked => {
                    submit();
                }
            }
        }

        function submit() {
            new(new_name.text, new_id.text);
            new_name.text = "";
            new_id.text = "";
        }
    }
}


export component NameMapTab inherits TabReload {
    reload() => {
        GNameMap.reload();
        Palette.background;
    }

    HorizontalBox {
        StringIdContainer {
            width: 30%;
            values: GNameMap.classes;
            delete(name) => {
                GNameMap.delete_class(name);
            }
            update(name, id) => {
                GNameMap.update_class_id(name, id);
            }
            new(name, id) => {
                GNameMap.new_class(name, id);
            }
        }

        StringIdContainer {
            width: 30%;
            values: GNameMap.states;
            delete(name) => {
                GNameMap.delete_state(name);
            }
            update(name, id) => {
                GNameMap.update_state_id(name, id);
            }
            new(name, id) => {
                GNameMap.new_state(name, id);
            }
        }

        StringIdContainer {
            width: 30%;
            values: GNameMap.events;
            delete(index) => {
                GNameMap.delete_event(index);
            }
            update(name, id) => {
                GNameMap.update_event_id(name, id);
            }
            new(name, id) => {
                GNameMap.new_event(name, id);
            }
        }
    }
}
