import {
    HorizontalBox,
    VerticalBox,
    LineEdit,
    Button,
    GridBox,
    ScrollView,
    Palette,
} from "std-widgets.slint";
import { TabReload } from "app_widgets.slint";


export struct StringId {
    name: string,
    id: string, // Do not use int, since it is just i32 while we need id is u64
}

export global GNameMap {
    in-out property <[StringId]> classes;
    in-out property <[StringId]> states;
    in-out property <[StringId]> events;

    pure callback reload();
    callback delete_class(string);
    callback delete_state(string);
    callback delete_event(string);
    callback update_class_id(string, string); // name, id
    callback update_state_id(string, string);
    callback update_event_id(string, string);
}


export component StringIdContainer inherits Rectangle {
    in-out property <[StringId]> values;

    callback delete(string);
    callback update(string, string); // name, id

    ScrollView {
        GridBox {
            for value[i] in values: Row {
                Text {
                    text: value.name;
                }

                edit := LineEdit {
                    text: value.id;
                    input-type: number;
                    accepted(text) => {
                        update(value.name, self.text);
                    }
                }

                Button {
                    text: "";
                    clicked => {
                        update(value.name, edit.text);
                    }
                }

                Button {
                    text: "Del";
                    clicked => {
                        delete(value.name);
                    }
                }
            }
        }
    }
}


export component NameMapContainer inherits TabReload {
    reload() => {
        GNameMap.reload();
        Palette.background;
    }

    HorizontalBox {
        StringIdContainer {
            width: 30%;
            values: GNameMap.classes;
            delete(name) => {
                GNameMap.delete_class(name);
            }
            update(name, id) => {
                GNameMap.update_class_id(name, id);
            }
        }

        StringIdContainer {
            width: 30%;
            values: GNameMap.states;
            delete(name) => {
                GNameMap.delete_state(name);
            }
            update(name, id) => {
                GNameMap.update_state_id(name, id);
            }
        }

        StringIdContainer {
            width: 30%;
            values: GNameMap.events;
            delete(index) => {
                GNameMap.delete_event(index);
            }
            update(name, id) => {
                GNameMap.update_event_id(name, id);
            }
        }
    }
}
