import {
    LineEdit,
    Button,
    GridBox,
    ScrollView,
    Palette,
    ListView,
} from "std-widgets.slint";
import { TabReload, EditableTextBox, SearchBox } from "app_widgets.slint";
import { Vertical, Horizontal, OutlinedCard } from "material-1.0/material.slint";


export struct StringId {
    name: string,
    id: string, // Do not use int, since it is just i32 while we need id is u64
}

export global GNameMap {
    in-out property <[StringId]> classes;
    in-out property <[StringId]> states;
    in-out property <[StringId]> events;

    callback delete_class(string);
    callback delete_state(string);
    callback delete_event(string);
    callback update_class_id(string, string); // name, id
    callback update_state_id(string, string);
    callback update_event_id(string, string);
    callback new_class(string, string); // name ,id
    callback new_state(string, string); // name ,id
    callback new_event(string, string); // name ,id
    callback search_class(string);
    callback search_state(string);
    callback search_event(string);
}


export component StringIdContainer inherits OutlinedCard {
    in-out property <[StringId]> values;

    callback delete(string);
    callback update(string, string); // name, id
    callback new(string, string);
    callback search(string);

    Vertical {
        SearchBox {
            search(text) => { root.search(text); }
        }

        ListView {
            for value[i] in values: Horizontal {
                // TODO: Allow rename
                Text {
                    text: value.name;
                }

                edit := LineEdit {
                    text: value.id;
                    input-type: number;
                    accepted(text) => {
                        update(value.name, self.text);
                    }
                }

                Button {
                    text: "";
                    clicked => {
                        update(value.name, edit.text);
                    }
                }

                Button {
                    text: "Del";
                    clicked => {
                        delete(value.name);
                    }
                }
            }
        }

        Horizontal {
            new_name := LineEdit {
                placeholder-text: "New name";

                accepted(text) => {
                    submit()
                }
            }

            new_id := LineEdit {
                placeholder-text: "New id";
                accepted(text) => {
                    submit()
                }
            }

            Button {
                text: "Add";
                clicked => {
                    submit();
                }
            }
        }

        function submit() {
            new(new_name.text, new_id.text);
            new_name.text = "";
            new_id.text = "";
        }
    }
}


export component NameMapTab inherits TabReload {
    in-out property <bool> is_saved;

    Horizontal {
        StringIdContainer {
            values: GNameMap.classes;
            delete(name) => {
                GNameMap.delete_class(name);
                is_saved = false;
            }
            update(name, id) => {
                GNameMap.update_class_id(name, id);
                is_saved = false;
            }
            new(name, id) => {
                GNameMap.new_class(name, id);
                is_saved = false;
            }
            search(text) => {
                GNameMap.search_class(text);
            }
        }

        StringIdContainer {
            values: GNameMap.states;
            delete(name) => {
                GNameMap.delete_state(name);
                is_saved = false;
            }
            update(name, id) => {
                GNameMap.update_state_id(name, id);
                is_saved = false;
            }
            new(name, id) => {
                GNameMap.new_state(name, id);
                is_saved = false;
            }
            search(text) => { GNameMap.search_state(text); }
        }

        StringIdContainer {
            values: GNameMap.events;
            delete(index) => {
                GNameMap.delete_event(index);
                is_saved = false;
            }
            update(name, id) => {
                GNameMap.update_event_id(name, id);
                is_saved = false;
            }
            new(name, id) => {
                GNameMap.new_event(name, id);
                is_saved = false;
            }
            search(text) => { GNameMap.search_event(text); }
        }
    }
}
