
import { VerticalBox, Palette } from "std-widgets.slint";

export struct Noti {
    level: int, // error, warning, info
    message: string,
}

export global GNoti {
    in-out property <Noti> noti;
}

export component NotiBox inherits PopupWindow {
    // TODO: stack notifications
    Rectangle {
        background: Palette.background;

        VerticalBox {
            padding: 2px;

            Text {
                text: GNoti.noti.message;
                color: {
                    if (GNoti.noti.level == 0) {
                        red
                    } else if (GNoti.noti.level == 1) {
                        orange
                    } else {
                        green
                    }
                };
            }
        }
    }
}
