
import { Palette } from "std-widgets.slint";
import { Vertical } from "material-1.0/material.slint";

export struct Noti {
    level: int, // error, warning, info
    message: string,
}

export global GNoti {
    in-out property <Noti> noti;
}

export component NotiBox inherits PopupWindow {
    // TODO: stack notifications
    Rectangle {
        background: Palette.background;

        Vertical {
            Text {
                text: GNoti.noti.message;
                color: {
                    if (GNoti.noti.level == 0) {
                        red
                    } else if (GNoti.noti.level == 1) {
                        orange
                    } else {
                        green
                    }
                };
            }
        }
    }
}
