import {
    TabReload,
    EditableTextBox,
    SelectableBox,
    SearchBox,
    SelectionBox,
} from "app_widgets.slint";
import {
    Palette,
    LineEdit,
    ListView,
    Button,
    ComboBox,
    TextEdit,
    HorizontalBox,
    VerticalBox,
    ScrollView,
} from "std-widgets.slint";
import {
    Vertical,
    Horizontal,
    OutlinedCard,
    ElevatedCard,
    IconButton,
    TextButton,
    FilledCard,
    ElevatedButton,
    HorizontalDivider,
    FloatingActionButton,
    InputChip,
} from "material-1.0/material.slint";
import { Icons } from "material-1.0/ui/icons/icons.slint";
import { VerticalDivider } from "material-1.0/ui/components/divider.slint";
import { GConfig } from "common.slint";
import { ListItem, Grid } from "material-1.0/material.slint";
import { SearchBar } from "material-1.0/ui/components/search_bar.slint";
import { GContent } from "content_tab.slint";

export struct UiSequenceItem {
    class: string,
    state: string,
    dialogue: string,
}

export struct SequenceInfo {
    name: string,
    id: string,
}

export global GSequence {
    in property <[string]> sequences;
    in property <[UiSequenceItem]> items;
    in property <SequenceInfo> info;
    in property <string> selected_sequence;

    callback add(string);
    callback select(string);
    callback delete(string);
    callback rename(string, string);
    callback search(string);

    callback delete_item(int);
    callback add_item(string, string, string);
}


export component SequenceTab inherits TabReload {
    in-out property <bool> is_saved;

    HorizontalLayout {
        Rectangle {
            width: 300px;

            VerticalLayout {
                SearchBox {
                    search(text) => { GSequence.search(text); }
                }

                ListView {
                    for sequence in GSequence.sequences: Rectangle {
                        EditableTextBox {
                            value: sequence;
                            selected: sequence == GSequence.selected_sequence;

                            submit(new_name) => { GSequence.rename(sequence, new_name); }
                            delete => { GSequence.delete(sequence); }
                            select => { GSequence.select(sequence); GSequence.selected_sequence = sequence; }
                        }
                    }
                }

                HorizontalLayout {
                    new_sequence_name := LineEdit {
                        placeholder-text: "New Sequence";
                    }

                    Button {
                        text: "Add";
                        clicked => { GSequence.add(new_sequence_name.text); }
                    }
                }
            }
        }

        VerticalDivider { }

        VerticalLayout {
            Text {
                text: GSequence.info.name;
            }

            HorizontalDivider { }

            Text {
                text: "APPEND NEW SEQUENCE STEP";
            }

            HorizontalLayout {
                new_item_class := SelectionBox {
                    placeholder-text: "Class";
                    items: GContent.class_list;
                    filter(text) => {
                        GContent.search_affect_class(text);
                    }
                }

                new_item_state := SelectionBox {
                    placeholder-text: "State";
                    items: GContent.state_list;
                    filter(text) => {
                        GContent.search_affect_state(new_item_class.text, text);
                    }
                }

                new_item_dialogue := LineEdit {
                    input-type: InputType.number;
                }

                Button {
                    text: "Add";
                    clicked => {
                        GSequence.add_item(new_item_class.text, new_item_state.text, new_item_dialogue.text);
                    }
                }
            }

            HorizontalDivider { }

            ListView {
                for item[id] in GSequence.items: Rectangle {
                    HorizontalLayout {
                        Text {
                            text: "#" + id;
                        }

                        Text {
                            text: item.class;
                        }

                        Text {
                            text: item.state;
                        }

                        Text {
                            text: item.dialogue;
                        }

                        IconButton {
                            clicked => { GSequence.delete_item(id); }
                        }
                    }
                }
            }
        }
    }
}
