
import { Horizontal, VerticalDivider } from "material-1.0/material.slint";
import { GFile } from "file_section.slint";

export component StatusBar inherits Rectangle {
    in property <bool> is_saved: true;

    Horizontal {
        alignment: LayoutAlignment.space-between;
        Text {
            text: {
                if is_saved {
                    "Saved"
                } else {
                    "* Unsave"
                }
            }
            horizontal-alignment: end;
        }
    }
}
