

import { GFile } from "file_section.slint";
import { HorizontalBox } from "std-widgets.slint";

export component StatusBar inherits Rectangle {
    in property <bool> is_saved: true;

    HorizontalBox {
        alignment: LayoutAlignment.space-between;
        Text {
            text: {
                if is_saved {
                    "Saved"
                } else {
                    "* Unsave"
                }
            }
            horizontal-alignment: end;
        }
    }
}
